"""Scaffolds — extend axiom-sdd without touching engine code.

add-tool     -> adapters/<id>/tool.json (registry extension) + docs/ folder where the
                team pastes the vendor's official documentation.
add-profile  -> profiles/<name>.yaml pre-commented, following the house schema.
add-template -> templates/<NAME>.md skeleton.
"""
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def _slug_ok(s: str) -> bool:
    return bool(re.fullmatch(r"[a-z][a-z0-9\-]{1,40}", s))


def add_tool(registry: dict) -> int:
    from . import ui
    ui.banner()
    print("\nRegistrar uma nova IA agentica (adapter). O que voce precisa saber antes:")
    print("  - como ela e detectada na maquina (comando no PATH e/ou pasta de instalacao);")
    print("  - quais arquivos de instrucao ela le no repositorio (ex.: AGENTS.md);")
    print("  - baixe a documentacao oficial e cole em adapters/<id>/docs/ ao final.\n")

    tid = ui.ask("id (kebab-case, ex.: gemini-cli)")
    if not _slug_ok(tid):
        print("erro: id invalido (use kebab-case)")
        return 2
    if tid in {t["id"] for t in registry["tools"]}:
        print(f"erro: '{tid}' ja existe no registry")
        return 2
    name = ui.ask("nome de exibicao", tid)
    kind = ui.menu("Tipo:", [("CLI (comando no PATH)", "cli"),
                             ("Plugin de IDE", "ide-plugin"),
                             ("Cloud (sem pegada local)", "cloud")])
    tool = {"id": tid, "name": name, "kind": kind, "reads": [], "shims": ["agents-md"]}
    if kind == "cli":
        tool["which"] = ui.ask("comando no PATH (ex.: gemini)", tid.split("-")[0])
    elif kind == "cloud":
        tool["always_offer"] = True
        tool["notes"] = "Cloud runtime: reads AGENTS.md from the git REMOTE; stealth-mode files never reach it."
    reads = ui.ask("arquivos que ela le no repo (separados por virgula)", "AGENTS.md")
    tool["reads"] = [r.strip() for r in reads.split(",") if r.strip()]
    extra = [s for s in registry["shims"] if s != "agents-md"]
    picks = ui.checkboxes("Shims adicionais a gerar para ela:",
                          [(s, s) for s in extra], set(), allow_empty=True)
    tool["shims"] += picks

    dest = ROOT / "adapters" / tid
    (dest / "docs").mkdir(parents=True, exist_ok=True)
    (dest / "tool.json").write_text(json.dumps(tool, indent=2, ensure_ascii=False) + "\n",
                                    encoding="utf-8")
    (dest / "docs" / "README.md").write_text(
        f"# {name} — documentacao oficial\n\n"
        "Cole aqui (arquivos .md) a documentacao oficial desta ferramenta que o time\n"
        "usou para preencher o tool.json: como ela le instrucoes de repositorio,\n"
        "comandos/skills, e limites (tamanho de contexto, arquivos suportados).\n"
        "Os agentes do SDD leem esta pasta quando precisam de detalhes do runtime.\n",
        encoding="utf-8")
    (dest / "ADAPTER.md").write_text(
        f"# {name} adapter\n\nGenerated by `axiom add-tool`. Source of truth: `tool.json` "
        "(merged into the registry at runtime).\nHonors the adapter contract in "
        "[adapters/README.md](../README.md). Vendor docs: [docs/](./docs/).\n",
        encoding="utf-8")
    print(f"\nOK: {dest / 'tool.json'} criado e ja ativo (o registry mescla adapters/*/tool.json).")
    print(f"Proximos passos: cole a documentacao oficial em {dest / 'docs'} e rode "
          f"'axiom doctor' para ver a deteccao; ajuste 'detect'/'version_glob' no tool.json se preciso.")
    return 0


PROFILE_SKELETON = """profile: {name}
summary: <uma linha: o que este profile entrega>
extends: _defaults
workflow: standard          # fast | standard | full | hotfix
change_budget: moderate     # minimal | moderate | broad
test_modes: [unit]          # ex.: [characterization, regression, plan-diff]
agents+: []                 # agentes extras alem do roster default, ex.: [architect]
gates+: []                  # gates extras, ex.: [architecture-compliant]
readiness_threshold: 80
context_requirements+: []
dor_extra: []               # Definition of Ready adicional
dod_extra: []               # Definition of Done adicional
evidence_expected+: []
token_budget: M             # S | M | L
"""


def add_profile(name: str) -> int:
    if not _slug_ok(name):
        print("erro: nome invalido (kebab-case)")
        return 2
    dest = ROOT / "profiles" / f"{name}.yaml"
    if dest.exists():
        print(f"erro: {dest} ja existe")
        return 2
    dest.write_text(PROFILE_SKELETON.format(name=name), encoding="utf-8")
    print(f"OK: {dest} criado. Preencha os campos comentados; "
          f"'axiom list-profiles' ja o lista.")
    return 0


def add_template(name: str) -> int:
    slug = name.upper().replace(" ", "-")
    dest = ROOT / "templates" / f"{slug}.md"
    if dest.exists():
        print(f"erro: {dest} ja existe")
        return 2
    dest.write_text(
        f"# {slug}\n\n> Template do axiom-sdd. Campos entre <> sao obrigatorios; "
        "marque lacunas como UNKNOWN / ASSUMPTION / NEEDS_CONFIRMATION — nunca invente.\n\n"
        "## Contexto\n<why>\n\n## Conteudo\n<what>\n\n## Evidencias\n<links/logs>\n",
        encoding="utf-8")
    print(f"OK: {dest} criado seguindo o padrao dos templates do axiom-sdd.")
    return 0
